import { FrightModule } from '#/api/system/permission';
import type { FieldPermissionProfile } from './field-permission';

/** 扁平表单和派生列到原始 DTO 的显式映射；新模块可追加同结构配置。 */
export const seaExportFieldPermission: FieldPermissionProfile = {
  module: FrightModule.SeaExport,
  nested: { transportOrder: FrightModule.TransportOrder },
  formDependencies: { vessel: ['innerVoyno'], pkgs: ['codePackageId'] },
  search: {
    keyword: [
      'vessel',
      'innerVoyno',
      'transportOrder.remark',
      'transportOrder.mblNum',
      'transportOrder.bookingNum',
      'transportOrder.contractNum',
      'transportOrder.invoiceNum',
      'transportOrder.commissionNum',
    ],
  },
  aliases: {
    orderctns: ['transportOrder.orderCtns'],
    ctnno: ['transportOrder.orderCtns'],
    goodscompletetime: ['transportOrder.goodsCompleteTime'],
    countryname: ['pod'],
    lanename: ['pod'],
    bltype: ['blType'],
    billtype: ['billType'],
    codeissuetypeid: ['issueType'],
    vessel: ['vessel'],
    innervoyno: ['innerVoyno'],
    terminalvoyno: ['terminalVoyno'],
    carrierid: ['carrierId', 'carrier'],
    secondnotifierid: ['secondNotifierId', 'secondNotifier'],
    secondnotifiercontent: ['secondNotifierContent'],
    podagentid: ['podAgentId', 'podAgent'],
    podagentcontent: ['podAgentContent'],
    bookingagentid: ['bookingAgentId', 'bookingAgent'],
    shipagentid: ['shipAgentId', 'shipAgent'],
    yardid: ['yardId', 'yard'],
    yardcontact: ['yardContact'],
    yardemail: ['yardEmail'],
    yardmobile: ['yardMobile'],
    yardtel: ['yardTel'],
    nobillenum: ['noBillEnum'],
    copynobillenum: ['copyNoBillEnum'],
    etd: ['transportOrder.etd'],
    atd: ['transportOrder.atd'],
    eta: ['transportOrder.eta'],
    closingtime: ['closingTime'],
    closevgmtime: ['closeVgmTime'],
    closedoctime: ['closeDocTime'],
    closemanifesttime: ['closeManifestTime'],
    signingtime: ['signingTime'],
    sortid: ['sortId'],
    remark: ['transportOrder.remark'],
    commissionnum: ['transportOrder.commissionNum'],
    mblnum: ['transportOrder.mblNum'],
    bookingnum: ['transportOrder.bookingNum'],
    contractnum: ['transportOrder.contractNum'],
    invoicenum: ['transportOrder.invoiceNum'],
    accountdate: ['transportOrder.accountDate'],
    settlementdate: ['transportOrder.settlementDate'],
    orgid: ['orgId', 'orgs'],
    codesourceid: ['transportOrder.codeSourceId', 'transportOrder.codeSource'],
    isbusinesslocking: ['transportOrder.isBusinessLocking'],
    feelocked: ['transportOrder.feeLocked'],
    codefrtid: ['transportOrder.codeFrtId', 'transportOrder.codeFrt'],
    codeserviceid: [
      'transportOrder.codeServiceId',
      'transportOrder.codeService',
    ],
    cargoid: ['transportOrder.cargoId'],
    tradetermstype: ['transportOrder.tradeTermsType'],
    polid: ['polId', 'pol'],
    polremark: ['polRemark'],
    podid: ['podId', 'pod'],
    podremark: ['podRemark'],
    pot1id: ['poT1Id', 'poT1'],
    pot1remark: ['poT1Remark'],
    pot2id: ['poT2Id', 'poT2'],
    pot2remark: ['poT2Remark'],
    receiveportid: ['receivePortId', 'receivePort'],
    receiveportremark: ['receivePortRemark'],
    deliverportid: ['deliverPortId', 'deliverPort'],
    deliverportremark: ['deliverPortRemark'],
    signingportid: ['signingPortId', 'signingPort'],
    clientid: ['transportOrder.clientId', 'transportOrder.client'],
    teamid: ['transportOrder.teamId', 'transportOrder.team'],
    custbrokerid: ['transportOrder.custBrokerId', 'transportOrder.custBroker'],
    warehouseid: ['transportOrder.warehouseId', 'transportOrder.warehouse'],
    insuranceid: ['transportOrder.insuranceId', 'transportOrder.insurance'],
    consigneeid: ['transportOrder.consigneeId', 'transportOrder.consignee'],
    consigneecontent: ['transportOrder.consigneeContent'],
    shipperid: ['transportOrder.shipperId', 'transportOrder.shipper'],
    shippercontent: ['transportOrder.shipperContent'],
    notifierid: ['transportOrder.notifierId', 'transportOrder.notifier'],
    notifiercontent: ['transportOrder.notifierContent'],
    marks: ['transportOrder.marks'],
    pkgs: ['transportOrder.pkgs'],
    codepackageid: [
      'transportOrder.codePackageId',
      'transportOrder.codePackage',
    ],
    goodsdes: ['transportOrder.goodsDes'],
    kgs: ['transportOrder.kgs'],
    cbm: ['transportOrder.cbm'],
    internalremark: ['transportOrder.internalRemark'],
    ordercodegoodss: ['transportOrder.orderCodeGoodss'],
    orderusers: ['transportOrder.orderUsers'],
    dglevel: ['transportOrder.dgLevel'],
    dgno: ['transportOrder.dgNo'],
    dgpageno: ['transportOrder.dgPageNo'],
    dglabel: ['transportOrder.dgLabel'],
    dgpackingcategory: ['transportOrder.dgPackingCategory'],
    dgcontact: ['transportOrder.dgContact'],
    dgtel: ['transportOrder.dgTel'],
    dgnetweight: ['transportOrder.dgNetWeight'],
    dgflashpoint: ['transportOrder.dgFlashPoint'],
    dgpackingno: ['transportOrder.dgPackingNo'],
    dgmarinepollution: ['transportOrder.dgMarinePollution'],
    reefertemperature: ['transportOrder.reeferTemperature'],
    reeferventilation: ['transportOrder.reeferVentilation'],
    reeferhumidity: ['transportOrder.reeferHumidity'],
    reefermintemperature: ['transportOrder.reeferMinTemperature'],
    reefermaxtemperature: ['transportOrder.reeferMaxTemperature'],
    reefertemperatureunit: ['transportOrder.reeferTemperatureUnit'],
    reeferventopen: ['transportOrder.reeferVentOpen'],
    codesourceidrange: [
      'transportOrder.codeSourceId',
      'transportOrder.codeSource',
    ],
    codeserviceidrange: [
      'transportOrder.codeServiceId',
      'transportOrder.codeService',
    ],
    custbrokeridrange: [
      'transportOrder.custBrokerId',
      'transportOrder.custBroker',
    ],
    warehouseidrange: [
      'transportOrder.warehouseId',
      'transportOrder.warehouse',
    ],
    insuranceidrange: [
      'transportOrder.insuranceId',
      'transportOrder.insurance',
    ],
    consigneeidrange: [
      'transportOrder.consigneeId',
      'transportOrder.consignee',
    ],
    codepackageidrange: [
      'transportOrder.codePackageId',
      'transportOrder.codePackage',
    ],
    operationusername: ['transportOrder.orderUsers'],
    saleusername: ['transportOrder.orderUsers'],
    businessusername: ['transportOrder.orderUsers'],
    customerserviceusername: ['transportOrder.orderUsers'],
    documentationusername: ['transportOrder.orderUsers'],
    carriercode: ['carrier', 'carrierCode'],
    prepareatid: ['transportOrder.prepareAtId'],
  },
};
export const seaImportFieldPermission: FieldPermissionProfile = {
  module: FrightModule.SeaImport,
  nested: { transportOrder: FrightModule.TransportOrder },
  formDependencies: { vessel: ['innerVoyno'], pkgs: ['codePackageId'] },
  search: {
    keyword: [
      'vessel',
      'innerVoyno',
      'batchNum',
      'transportOrder.remark',
      'transportOrder.mblNum',
      'transportOrder.bookingNum',
      'transportOrder.contractNum',
      'transportOrder.invoiceNum',
      'transportOrder.commissionNum',
    ],
  },
  aliases: {
    orderctns: ['orderCtns'],
    ctnno: ['orderCtns'],
    goodscompletetime: ['transportOrder.goodsCompleteTime'],
    vessel: ['vessel'],
    innervoyno: ['innerVoyno'],
    terminalvoyno: ['terminalVoyno'],
    carrierid: ['carrierId', 'carrier'],
    polid: ['polId', 'pol'],
    polremark: ['polRemark'],
    podid: ['podId', 'pod'],
    podremark: ['podRemark'],
    clientnum: ['clientNum'],
    terminalid: ['terminalId', 'terminal'],
    throughbillnum: ['throughBillNum'],
    hblnum: ['hblNum'],
    trademode: ['tradeMode'],
    batchnum: ['batchNum'],
    origincountryid: ['originCountryId', 'originCountry'],
    totalnetweight: ['totalNetWeight'],
    exchangebilldate: ['exchangeBillDate'],
    pickupdate: ['pickUpDate'],
    customsdeclaredate: ['customsDeclareDate'],
    transferstationdate: ['transferStationDate'],
    freedays: ['freeDays'],
    ctnusedate: ['ctnUseDate'],
    sortid: ['sortId'],
    orgid: ['orgId', 'orgs'],
    lanename: ['pol'],
    countryname: ['pol'],
    commissionnum: ['transportOrder.commissionNum'],
    accountdate: ['transportOrder.accountDate'],
    settlementdate: ['transportOrder.settlementDate'],
    codesourceid: ['transportOrder.codeSourceId', 'transportOrder.codeSource'],
    codeserviceid: [
      'transportOrder.codeServiceId',
      'transportOrder.codeService',
    ],
    isbusinesslocking: ['transportOrder.isBusinessLocking'],
    isunfinished: ['transportOrder.isUnfinished'],
    feelocked: ['transportOrder.feeLocked'],
    mblnum: ['transportOrder.mblNum'],
    bookingnum: ['transportOrder.bookingNum'],
    contractnum: ['transportOrder.contractNum'],
    internalremark: ['transportOrder.internalRemark'],
    remark: ['transportOrder.remark'],
    marks: ['transportOrder.marks'],
    goodsdes: ['transportOrder.goodsDes'],
    pkgs: ['transportOrder.pkgs'],
    upperpkgs: ['transportOrder.upperPKGS'],
    codepackageid: [
      'transportOrder.codePackageId',
      'transportOrder.codePackage',
    ],
    kgs: ['transportOrder.kgs'],
    cbm: ['transportOrder.cbm'],
    cargoid: ['transportOrder.cargoId'],
    etd: ['transportOrder.etd'],
    clientid: ['transportOrder.clientId', 'transportOrder.client'],
    clientcontactid: [
      'transportOrder.clientContactId',
      'transportOrder.clientContact',
    ],
    teamid: ['transportOrder.teamId', 'transportOrder.team'],
    custbrokerid: ['transportOrder.custBrokerId', 'transportOrder.custBroker'],
    warehouseid: ['transportOrder.warehouseId', 'transportOrder.warehouse'],
    insuranceid: ['transportOrder.insuranceId', 'transportOrder.insurance'],
    consigneeid: ['transportOrder.consigneeId', 'transportOrder.consignee'],
    consigneecontent: ['transportOrder.consigneeContent'],
    shipperid: ['transportOrder.shipperId', 'transportOrder.shipper'],
    shippercontent: ['transportOrder.shipperContent'],
    notifierid: ['transportOrder.notifierId', 'transportOrder.notifier'],
    notifiercontent: ['transportOrder.notifierContent'],
    ordercodegoodss: ['transportOrder.orderCodeGoodss'],
    ordercodegoodsrows: ['transportOrder.orderCodeGoodss'],
    orderusers: ['transportOrder.orderUsers'],
    dglevel: ['transportOrder.dgLevel'],
    dgno: ['transportOrder.dgNo'],
    dgpageno: ['transportOrder.dgPageNo'],
    dglabel: ['transportOrder.dgLabel'],
    dgpackingcategory: ['transportOrder.dgPackingCategory'],
    dgcontact: ['transportOrder.dgContact'],
    dgtel: ['transportOrder.dgTel'],
    dgnetweight: ['transportOrder.dgNetWeight'],
    dgflashpoint: ['transportOrder.dgFlashPoint'],
    dgpackingno: ['transportOrder.dgPackingNo'],
    dgmarinepollution: ['transportOrder.dgMarinePollution'],
    reefertemperature: ['transportOrder.reeferTemperature'],
    reeferventilation: ['transportOrder.reeferVentilation'],
    reeferhumidity: ['transportOrder.reeferHumidity'],
    reefermintemperature: ['transportOrder.reeferMinTemperature'],
    reefermaxtemperature: ['transportOrder.reeferMaxTemperature'],
    reefertemperatureunit: ['transportOrder.reeferTemperatureUnit'],
    reeferventopen: ['transportOrder.reeferVentOpen'],
    codesourceidrange: [
      'transportOrder.codeSourceId',
      'transportOrder.codeSource',
    ],
    codeserviceidrange: [
      'transportOrder.codeServiceId',
      'transportOrder.codeService',
    ],
    codepackageidrange: [
      'transportOrder.codePackageId',
      'transportOrder.codePackage',
    ],
    clientcontactidrange: [
      'transportOrder.clientContactId',
      'transportOrder.clientContact',
    ],
    custbrokeridrange: [
      'transportOrder.custBrokerId',
      'transportOrder.custBroker',
    ],
    warehouseidrange: [
      'transportOrder.warehouseId',
      'transportOrder.warehouse',
    ],
    insuranceidrange: [
      'transportOrder.insuranceId',
      'transportOrder.insurance',
    ],
    consigneeidrange: [
      'transportOrder.consigneeId',
      'transportOrder.consignee',
    ],
    operationusername: ['transportOrder.orderUsers'],
    saleusername: ['transportOrder.orderUsers'],
    businessusername: ['transportOrder.orderUsers'],
    customerserviceusername: ['transportOrder.orderUsers'],
    documentationusername: ['transportOrder.orderUsers'],
    carriercode: ['carrier', 'carrierCode'],
    prepareatid: ['transportOrder.prepareAtId'],
  },
};
export const airExportFieldPermission: FieldPermissionProfile = {
  module: FrightModule.AirExport,
  nested: { transportOrder: FrightModule.TransportOrder },
  formDependencies: { vessel: ['innerVoyno'], pkgs: ['codePackageId'] },
  search: {
    keyword: [
      'flightNo',
      'transportOrder.remark',
      'transportOrder.mblNum',
      'transportOrder.contractNum',
      'transportOrder.invoiceNum',
      'transportOrder.commissionNum',
    ],
  },
  aliases: {
    orderctns: ['orderCtns'],
    ctnno: ['orderCtns'],
    goodscompletetime: ['transportOrder.goodsCompleteTime'],
    bookingagentid: ['bookingAgentId', 'bookingAgent'],
    flightno: ['flightNo'],
    polid: ['polId', 'pol'],
    polremark: ['polRemark'],
    potid: ['potId', 'pot'],
    potremark: ['potRemark'],
    podid: ['podId', 'pod'],
    podremark: ['podRemark'],
    bubbleratio: ['bubbleRatio'],
    customsdeclaredate: ['customsDeclareDate'],
    deliverywarehousedate: ['deliveryWarehouseDate'],
    sortid: ['sortId'],
    orgid: ['orgId', 'orgs'],
    commissionnum: ['transportOrder.commissionNum'],
    inputtype: ['transportOrder.inputType'],
    accountdate: ['transportOrder.accountDate'],
    settlementdate: ['transportOrder.settlementDate'],
    codesourceid: ['transportOrder.codeSourceId', 'transportOrder.codeSource'],
    codeserviceid: [
      'transportOrder.codeServiceId',
      'transportOrder.codeService',
    ],
    isbusinesslocking: ['transportOrder.isBusinessLocking'],
    isunfinished: ['transportOrder.isUnfinished'],
    feelocked: ['transportOrder.feeLocked'],
    mblnum: ['transportOrder.mblNum'],
    contractnum: ['transportOrder.contractNum'],
    invoicenum: ['transportOrder.invoiceNum'],
    internalremark: ['transportOrder.internalRemark'],
    remark: ['transportOrder.remark'],
    marks: ['transportOrder.marks'],
    goodsdes: ['transportOrder.goodsDes'],
    pkgs: ['transportOrder.pkgs'],
    upperpkgs: ['transportOrder.upperPKGS'],
    codepackageid: [
      'transportOrder.codePackageId',
      'transportOrder.codePackage',
    ],
    kgs: ['transportOrder.kgs'],
    cbm: ['transportOrder.cbm'],
    cargoid: ['transportOrder.cargoId'],
    etd: ['transportOrder.etd'],
    atd: ['transportOrder.atd'],
    eta: ['transportOrder.eta'],
    clientid: ['transportOrder.clientId', 'transportOrder.client'],
    teamid: ['transportOrder.teamId', 'transportOrder.team'],
    custbrokerid: ['transportOrder.custBrokerId', 'transportOrder.custBroker'],
    warehouseid: ['transportOrder.warehouseId', 'transportOrder.warehouse'],
    insuranceid: ['transportOrder.insuranceId', 'transportOrder.insurance'],
    consigneeid: ['transportOrder.consigneeId', 'transportOrder.consignee'],
    consigneecontent: ['transportOrder.consigneeContent'],
    shipperid: ['transportOrder.shipperId', 'transportOrder.shipper'],
    shippercontent: ['transportOrder.shipperContent'],
    notifierid: ['transportOrder.notifierId', 'transportOrder.notifier'],
    notifiercontent: ['transportOrder.notifierContent'],
    ordercodegoodss: ['transportOrder.orderCodeGoodss'],
    orderusers: ['transportOrder.orderUsers'],
    dglevel: ['transportOrder.dgLevel'],
    dgno: ['transportOrder.dgNo'],
    dgpageno: ['transportOrder.dgPageNo'],
    dglabel: ['transportOrder.dgLabel'],
    dgpackingcategory: ['transportOrder.dgPackingCategory'],
    dgcontact: ['transportOrder.dgContact'],
    dgtel: ['transportOrder.dgTel'],
    dgnetweight: ['transportOrder.dgNetWeight'],
    dgflashpoint: ['transportOrder.dgFlashPoint'],
    dgpackingno: ['transportOrder.dgPackingNo'],
    dgmarinepollution: ['transportOrder.dgMarinePollution'],
    reefertemperature: ['transportOrder.reeferTemperature'],
    reeferventilation: ['transportOrder.reeferVentilation'],
    reeferhumidity: ['transportOrder.reeferHumidity'],
    reefermintemperature: ['transportOrder.reeferMinTemperature'],
    reefermaxtemperature: ['transportOrder.reeferMaxTemperature'],
    reefertemperatureunit: ['transportOrder.reeferTemperatureUnit'],
    reeferventopen: ['transportOrder.reeferVentOpen'],
    codesourceidrange: [
      'transportOrder.codeSourceId',
      'transportOrder.codeSource',
    ],
    codeserviceidrange: [
      'transportOrder.codeServiceId',
      'transportOrder.codeService',
    ],
    codepackageidrange: [
      'transportOrder.codePackageId',
      'transportOrder.codePackage',
    ],
    custbrokeridrange: [
      'transportOrder.custBrokerId',
      'transportOrder.custBroker',
    ],
    warehouseidrange: [
      'transportOrder.warehouseId',
      'transportOrder.warehouse',
    ],
    insuranceidrange: [
      'transportOrder.insuranceId',
      'transportOrder.insurance',
    ],
    consigneeidrange: [
      'transportOrder.consigneeId',
      'transportOrder.consignee',
    ],
    operationusername: ['transportOrder.orderUsers'],
    saleusername: ['transportOrder.orderUsers'],
    businessusername: ['transportOrder.orderUsers'],
    customerserviceusername: ['transportOrder.orderUsers'],
    documentationusername: ['transportOrder.orderUsers'],
    carriercode: ['carrier', 'carrierCode'],
    prepareatid: ['transportOrder.prepareAtId'],
  },
};
export const orderFeeFieldPermission: FieldPermissionProfile = {
  module: FrightModule.OrderFee,
  aliases: {
    unitpricestr: ['unitPrice'],
    amountstr: ['amount'],
    notaxunitpricestr: ['noTaxUnitPrice'],
    notaxamountstr: ['noTaxAmount'],
    settlementname: ['settlement', 'settlementId'],
    settlementid: ['settlement', 'settlementId'],
    currencyname: ['currency', 'currencyId'],
    currencyid: ['currency', 'currencyId'],
    feecodename: ['feeCode', 'feeCodeId'],
    feecodeid: ['feeCode', 'feeCodeId'],
  },
};
export const freightRateFieldPermission: FieldPermissionProfile = {
  module: FrightModule.SeFreiPrice,
  /** 箱型子表独立模块；成本等字段配在 SeFreiPriceCtn，PropName 写 Cost 而非路径 */
  nested: { seFreiPriceCtns: FrightModule.SeFreiPriceCtn },
  /** 成本+指导价同列：仅两者都无条件屏蔽时才整列隐藏 */
  prefixes: {
    ctnSug_: { paths: ['seFreiPriceCtns.sugPrice'], mode: 'any' },
    /** 列表同格：成本+指导价都屏蔽才整列隐藏 */
    ctn_: {
      paths: ['seFreiPriceCtns.cost', 'seFreiPriceCtns.sugPrice'],
      mode: 'all',
    },
  },
  aliases: {
    'currency.code': ['currency', 'currencyId'],
    currencyid: ['currency', 'currencyId'],
    'country.countryName': ['country', 'countryId'],
    'bookingAgent.name': ['bookingAgent', 'bookingAgentId'],
    'poT1.portName': ['poT1', 'poT1Id'],
    'poT2.portName': ['poT2', 'poT2Id'],
    pot1id: ['poT1', 'poT1Id'],
    pot2id: ['poT2', 'poT2Id'],
    surchargefees: ['seFreiPriceFees'],
    etd: ['seFreiPriceDays', 'seFreiPriceWeekDays'],
    closedoctime: ['seFreiPriceDays', 'seFreiPriceWeekDays'],
    closingtime: ['seFreiPriceDays', 'seFreiPriceWeekDays'],
    validtimerange: ['validTimeStart', 'validTimeEnd'],
    podfreedayscombined: ['podFreeDays', 'poddem', 'poddet'],

    carrierid: ['carrierId', 'carrier'],
    polid: ['polId', 'pol'],
    podid: ['podId', 'pod'],
    bookingagentid: ['bookingAgentId', 'bookingAgent'],
    'carrier.enName': ['carrierId', 'carrier'],
    'pol.portName': ['polId', 'pol'],
    'pod.portName': ['podId', 'pod'],
  },
};
